services:

  db:
    image: postgres:16-alpine
    container_name: skills-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network
    restart: unless-stopped

  backend:
    image: ghcr.io/rahafabualrub/skills_utilization-backend:latest
    container_name: skills-backend
    ports:
      - "5000:5000"
    environment:
      PYTHONPATH: "/app/backend"
      VAULT_ADDR: "http://vault:8200"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  shared-network:
