name: Skills Utilization CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version

      - name: Check Docker Compose
        run: docker compose version

      - name: Build and start services
        run: |
          sudo docker compose up -d --build

      - name: Show running containers
        run: |
          sudo docker compose ps
