name: Skills Utilization CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  test:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Create Python virtual environment
        run: |
          python3 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip

      - name: Install backend dependencies
        run: |
          .venv/bin/pip install -r backend/requirements.txt

      - name: Test Python syntax
        run: |
          .venv/bin/python -m compileall backend

      - name: Check Docker
        run: docker --version

      - name: Check Docker Compose
        run: docker compose version


  build-and-push:
    name: Build and Push to GHCR
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ghcr.io/rahafabualrub/skills_utilization-backend:latest


  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Vault script
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: bash /home/aau/Desktop/project3/vault/vault.sh

      - name: Stop existing containers
        run: docker compose down

      - name: Deploy application
        run: docker compose up -d

      - name: Deployment status
        run: echo "Deployment completed successfully!"
